# Generated by Django 5.1.4 on 2025-01-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
